import {
  pgTable, text, serial, integer, boolean, timestamp, unique,
} from "drizzle-orm/pg-core";
import { profilesTable } from "./profiles";
import { rolesTable } from "./roles";

/**
 * permissions — every (module, action) pair that can be toggled.
 * Seed data is generated by seed-permissions.ts on first boot.
 */
export const permissionsTable = pgTable("permissions", {
  id:          serial("id").primaryKey(),
  module:      text("module").notNull(),
  action:      text("action").notNull(),
  description: text("description"),
}, t => [
  unique("permissions_module_action").on(t.module, t.action),
]);

/**
 * role_permissions — the configurable matrix managed by super_admin.
 * Every (role, permission) pair is explicitly stored so the UI can show
 * both granted and denied checkboxes.
 */
export const rolePermissionsTable = pgTable("role_permissions", {
  id:           serial("id").primaryKey(),
  roleName:     text("role_name").notNull().references(() => rolesTable.name),
  permissionId: integer("permission_id").notNull().references(() => permissionsTable.id),
  granted:      boolean("granted").notNull().default(true),
}, t => [
  unique("role_perm_unique").on(t.roleName, t.permissionId),
]);

/**
 * user_permissions — per-user overrides layered on top of role defaults.
 * Super_admin can grant extra permissions or explicitly deny role-granted ones.
 * Super_admin accounts may not have overrides applied.
 */
export const userPermissionsTable = pgTable("user_permissions", {
  id:                  serial("id").primaryKey(),
  profileId:           integer("profile_id").notNull().references(() => profilesTable.id),
  permissionId:        integer("permission_id").notNull().references(() => permissionsTable.id),
  granted:             boolean("granted").notNull(),
  grantedByProfileId:  integer("granted_by_profile_id").references(() => profilesTable.id),
  grantedAt:           timestamp("granted_at", { withTimezone: true }).notNull().defaultNow(),
}, t => [
  unique("user_perm_unique").on(t.profileId, t.permissionId),
]);

export type Permission     = typeof permissionsTable.$inferSelect;
export type RolePermission = typeof rolePermissionsTable.$inferSelect;
export type UserPermission = typeof userPermissionsTable.$inferSelect;
